{{- $namespace := .Values.namespace }}

{{- range $key, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  namespace: {{ $namespace }}
type: Opaque
data:
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}